project_title: VideoManipulation

model:
  base_learning_rate: 2.0e-6
  target: dicomogan.models.tmp_dicomoclip.DiCoMOGANCLIP
  project : "video-manipulation"

  params:
    # tgt_text : 'Yellow Dresses Made from polyester with V-neckline. The dress is all over ribbed and has front buttons and is short sleeves. The dress is regular fit'
    frame_log_size : [256, 256]
    video_length : 40
    delta_inversion_weight : 0.1
    l2_latent_eps : 0.02
    beta: 8

    lambda_vgg: 10.0
    l2_latent_lambda : 1.0

    clip_loss_lambda:
      target: dicomogan.models.utils.LambdaScheduler
      params:
        warm_up_steps: 25000
        lr_min: 0.01
        lr_max: 1.0
        max_decay_steps: 75000

    consistency_lambda:
      target: dicomogan.models.utils.LambdaScheduler
      params:
        warm_up_steps: 0
        lr_min: 0.01
        lr_max: 1.0
        max_decay_steps: 75000

    rec_loss_lambda:
      target: dicomogan.models.utils.LambdaScheduler
      params:
        warm_up_steps: 25000
        lr_min: 0.01
        lr_max: 1.0
        max_decay_steps: 75000
    
    video_ecnoder_config:
      target: dicomogan.new_modules.EncoderVideo_LatentODE
      params:
        img_size : [128, 128] # must match video_decoder
        static_latent_dim : 64
        dynamic_latent_dim : 64 # must match ODE_func_config latent_dim
        hid_channels : 32 
        kernel_size : 4
        hidden_dim : 256
        netE_num_downsampling_sp : 4
        netE_num_downsampling_gl : 1
        spatial_code_ch : 256
        global_code_ch : 512
        sampling_type: "Static"

    stylegan_gen_config:
      target: dicomogan.models.stylegan.StyleGAN2Face
      params:
        pkl_file: /scratch/users/abond19/VideoEditing/aligning_face_videos/StyleCLIP/stylegan2-ffhq-config-f.pt
    
    #mapping_config:
    #  target: dicomogan.modules.MappingNetworkVAE
    #  params:
    #    input_dim : 64 # must match dynamic_latent + (static_latent - text_latent)
    #    fsize : 256

    style_mapper_config:
      target: dicomogan.models.mapper.TripleAttributeMapper
      params:
        predict_delta: True
        use_coarse_mapper: [True, True, False] # Since the coarse mapper only handles pose, we don't want to do any modulation
        use_medium_mapper: [True, True, False]
        use_fine_mapper: [True, False, False] 
        coarse_cut_flag: False 
        medium_cut_flag: False
        fine_cut_flag: False
        mod_shape : [[1, 4, 1], [1, 4, 1], [1, 10, 1]]
        num_of_layers : [5, 5, 5]
        attr_vec_dims: [512, 64, 0] #much match W_cont + CLIP embedding


    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2 # MUST Match batch size in dataset
    num_workers: 40
    train:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: /kuacc/users/abond19/datasets/RAVDESS/train_split.txt
        img_root: /scratch/users/abond19/datasets/RAVDESS/Aligned
        inverted_img_root : /scratch/users/abond19/datasets/RAVDESS/Aligned
        inversion_root: /kuacc/users/abond19/datasets/w+_face_dataset
        skip_frames : 5
        n_sampled_frames : 4
        irregular_sampling : True
        batch_size : 2 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 256]
        # attribute : "Color"
        # attribute_stats : 'data/fashion/attributes_stats.yaml'

    validation:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: /kuacc/users/abond19/datasets/RAVDESS/test_split.txt
        img_root: /scratch/users/abond19/datasets/RAVDESS/Aligned
        inverted_img_root : /scratch/users/abond19/datasets/RAVDESS/Aligned
        inversion_root: /kuacc/users/abond19/datasets/w+_face_dataset
        skip_frames : 5
        n_sampled_frames : 10
        irregular_sampling : False
        batch_size : 2 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 256]
        # attribute : "Color"
        # attribute_stats : 'data/fashion/attributes_stats.yaml'


lightning:
  trainer:
    limit_val_batches : 2
    replace_sampler_ddp : False
    # precision : 32

