project_title: VideoManipulation

model:
  base_learning_rate: 2.0e-6
  target: dicomogan.models.new_dicomogan.New_DiCoMOGAN
  project : "video-manipulation"

  params:
    # tgt_text : 'Yellow Dresses Made from polyester with V-neckline. The dress is all over ribbed and has front buttons and is short sleeves. The dress is regular fit'
    delta_inversion_weight : 0.05
    rec_loss_lambda : 1.0
    l2_latent_lambda : 0.5
    clip_loss_lambda : 5.0
    l2_latent_eps : 0.03

    generator_config:
      target: dicomogan.models.stylegan.StyleGAN2Generator
      params:
        pkl_file: /kuacc/users/abond19/VideoEditing/dicomogan/StyleGAN_Human/ckpts/stylegan_human_v2_1024.pkl
    
    mapping_config:
      target: dicomogan.models.mapper.AttributeMapper
      params:
        predict_delta: True

        use_coarse_mapper: False # Since the coarse mapper only handles pose, we don't want to do any modulation
        use_medium_mapper: True
        use_fine_mapper: True
        coarse_cut_flag: False 
        medium_cut_flag: False
        fine_cut_flag: False
        attr_vec_dim: 512


    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3 # MUST Match batch size in dataset
    num_workers: 10
    train:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: data/fashion/fashion_train_videos.txt
        img_root: /kuacc/users/abond19/datasets/inverted_fashion_dataset
        inversion_root: /kuacc/users/abond19/datasets/w+_fashion_dataset/fashion/PTI/
        n_sampled_frames : 3
        batch_size : 3 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 192]
        attribute : "Color"
        attribute_stats : 'data/fashion/attributes_stats.yaml'

    validation:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: data/fashion/fashion_test_videos.txt
        img_root: /kuacc/users/abond19/datasets/inverted_fashion_dataset
        inversion_root: /kuacc/users/abond19/datasets/w+_fashion_dataset/fashion/PTI/
        n_sampled_frames : 3
        batch_size : 3 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 192]
        attribute : "Color"
        attribute_stats : 'data/fashion/attributes_stats.yaml'


lightning:
  trainer:
    limit_val_batches : 2
    replace_sampler_ddp : False
