project_title: VideoManipulation

model:
  base_learning_rate: 2.0e-6
  target: dicomogan.models.tmp_dicomoclip.DiCoMOGANCLIP
  project : "video-manipulation"

  params:
    # tgt_text : 'Yellow Dresses Made from polyester with V-neckline. The dress is all over ribbed and has front buttons and is short sleeves. The dress is regular fit'
    delta_inversion_weight : 0.1
    l2_latent_eps : 0.1

    lambda_vgg: 2.0
    lambda_G: 1
    lambda_bvae: 1
    rec_loss_lambda : 5.0
    l2_latent_lambda : 5.0
    clip_loss_lambda : 1.0
    consistency_lambda : 0.5
    
    vae_cond_dim : 16 # must match text encoder latent_dim
    beta: 8

    ODE_func_config:
      target: dicomogan.modules.LatentODEfunc
      params:
        latent_dim : 8 # must match dynamic_latent_dim
        nhidden : 20 

    video_ecnoder_config:
      target: dicomogan.modules.EncoderVideo_LatentODE
      params:
        img_size : [3,128,96] # must match video_decoder
        static_latent_dim : 24
        dynamic_latent_dim : 8 # must match ODE_func_config latent_dim
        hid_channels : 32 
        kernel_size : 4
        hidden_dim : 256
    
    video_decoder_config:
      target: dicomogan.modules.Decoder
      params:
        img_size : [3,128,96] # must match video_encoder
        latent_dim : 32 # should match static_latent_dim + dynamic_latent_dim

    text_encoder_config:
      target: dicomogan.modules.TextEncoder
      params:
        text_size : 512
        latent_dim : 16 # must match vae_cond_enc

    stylegan_gen_config:
      target: dicomogan.models.stylegan.StyleGAN2Generator
      params:
        pkl_file: /kuacc/users/abond19/VideoEditing/dicomogan/StyleGAN_Human/ckpts/stylegan_human_v2_1024.pkl
    
    mapping_config:
      target: dicomogan.modules.MappingNetworkVAE
      params:
        input_dim : 16 # must match dynamic_latent + (static_latent - text_latent)
        fsize : 256

    style_mapper_config:
      target: dicomogan.models.mapper.DoubleAttributeMapper
      params:
        predict_delta: True

        use_coarse_mapper: [True, False] # Since the coarse mapper only handles pose, we don't want to do any modulation
        use_medium_mapper: [True, True]
        use_fine_mapper: [False, True] 
        coarse_cut_flag: False 
        medium_cut_flag: False
        fine_cut_flag: False
        attr_vec_dim1: 256 # much match W_cont + CLIP embedding
        attr_vec_dim2: 512 # much match W_cont + CLIP embedding


    
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3 # MUST Match batch size in dataset
    num_workers: 10
    train:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: data/fashion/fashion_train_videos.txt
        img_root: /kuacc/users/abond19/datasets/aligned_fashion_dataset
        inverted_img_root : /kuacc/users/abond19/datasets/inverted_fashion_dataset
        inversion_root: /kuacc/users/abond19/datasets/w+_fashion_dataset/fashion/PTI/
        skip_frames : 5
        n_sampled_frames : 7
        irregular_sampling : True
        batch_size : 3 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 192]
        # attribute : "Color"
        attribute_stats : 'data/fashion/attributes_stats.yaml'

    validation:
      target: dicomogan.data.new_video.VideoDataFashion # Changed from data.video.VideoDataFashion to data.new_video.VideoDataFashion
      params:
        video_list: data/fashion/fashion_test_videos.txt
        img_root: /kuacc/users/abond19/datasets/aligned_fashion_dataset
        inverted_img_root : /kuacc/users/abond19/datasets/inverted_fashion_dataset
        inversion_root: /kuacc/users/abond19/datasets/w+_fashion_dataset/fashion/PTI/
        skip_frames : 5
        n_sampled_frames : 10
        irregular_sampling : False
        batch_size : 3 #MUST match batch size 
        # crop : [512, 384]
        size : [256, 192]
        # attribute : "Color"
        attribute_stats : 'data/fashion/attributes_stats.yaml'


lightning:
  trainer:
    limit_val_batches : 2
    replace_sampler_ddp : False
